CREATE TABLE account (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         username VARCHAR(255) NOT NULL,
                         password VARCHAR(255) NOT NULL,
                         CONSTRAINT pk_account PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_account_username_unique_lower ON account (LOWER(username));

CREATE TABLE account_roles (
                               account_id BIGINT NOT NULL,
                               role VARCHAR(50) NOT NULL,
                               CONSTRAINT pk_account_roles PRIMARY KEY (account_id, role),
                               CONSTRAINT fk_account_roles_account FOREIGN KEY (account_id) REFERENCES account(id)
);